### ISSUE TITLE
Recursive Mixins broken

### ISSUE THREAD

**Issue by micgro42** [MarcusSchwarz/lesserphp#13]
Hey,

thank you for maintaining lesserphp :-)

However, there seems to be a regression: Recursive mixins are now broken.

An example that works in the original leafo/lessphp, but is broken in this repository:

```less
div {
	.loop-grid-columns(4, class, width);
}

@grid-columns: 12;


.loop-grid-columns(@index, @class, @type) when (@index >= 0) {
    .calc-grid-column(@index, @class, @type);
    // next iteration
    .loop-grid-columns((@index - 1), @class, @type);
}

.calc-grid-column(@index, @class, @type) when (@type = width) and (@index > 0) {
    .col-@{class}-@{index} {
        width: percentage((@index / @grid-columns));
    }
}
```

expected outcome (see it at [less2css.org](http://less2css.org/#%7B%22less%22%3A%22div%20%7B%5Cn%5Ct.loop-grid-columns(4%2C%20class%2C%20width)%3B%5Cn%7D%5Cn%5Cn%40grid-columns%3A%2012%3B%5Cn%5Cn%5Cn.loop-grid-columns(%40index%2C%20%40class%2C%20%40type)%20when%20(%40index%20%3E%3D%200)%20%7B%5Cn%20%20%20%20.calc-grid-column(%40index%2C%20%40class%2C%20%40type)%3B%5Cn%20%20%20%20%2F%2F%20next%20iteration%5Cn%20%20%20%20.loop-grid-columns((%40index%20-%201)%2C%20%40class%2C%20%40type)%3B%5Cn%7D%5Cn%5Cn.calc-grid-column(%40index%2C%20%40class%2C%20%40type)%20when%20(%40type%20%3D%20width)%20and%20(%40index%20%3E%200)%20%7B%5Cn%20%20%20%20.col-%40%7Bclass%7D-%40%7Bindex%7D%20%7B%5Cn%20%20%20%20%20%20%20%20width%3A%20percentage((%40index%20%2F%20%40grid-columns))%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%7D)):

```css
div .col-class-4 {
  width: 33.33333333%;
}
div .col-class-3 {
  width: 25%;
}
div .col-class-2 {
  width: 16.66666667%;
}
div .col-class-1 {
  width: 8.33333333%;
}
```

However the repo MarcusSchwarz/lesserphp gives me the error `.calc-grid-column is undefined: failed at `.calc-grid-column(@index, @class, @type);`  in mixins.less at line 9`
